// src/app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; // Importa o Header
import Footer from "@/components/Footer"; // Importa o Footer

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elo Sapiens",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} bg-white text-gray-800 flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow container mx-auto max-w-7xl px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
